name: Flutter CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  android:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      # 🔥 ENV decide (same as your launch.json)
      - name: Set ENV
        id: env
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "ENV=dev" >> $GITHUB_OUTPUT
          else
            echo "ENV=staging" >> $GITHUB_OUTPUT
          fi

      # 🔹 Build APK
      - name: Build APK
        run: |
          flutter build apk --release \
          --dart-define=ENV=${{ steps.env.outputs.ENV }} \
          --dart-define=BASE_URL=${{ secrets.BASE_URL }} \
          --dart-define=API_KEY=${{ secrets.API_KEY }} \
          --dart-define=feature_flags=show_logs

      # 🔹 Build AAB only for prod
      - name: Build AAB (prod only)
        if: github.ref == 'refs/heads/main'
        run: |
          flutter build appbundle --release \
          --dart-define=ENV=prod \
          --dart-define=BASE_URL=${{ secrets.BASE_URL }} \
          --dart-define=API_KEY=${{ secrets.API_KEY }}

      # 🔹 Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ steps.env.outputs.ENV }}-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 🔹 Upload AAB
      - name: Upload AAB
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: app-prod-aab
          path: build/app/outputs/bundle/release/app-release.aab