name: iOS CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'

      - name: Install Dependencies
        run: flutter pub get

      - name: Install Pods
        run: |
          cd ios
          pod install
          cd ..

      # 🔥 ENV same as Android
      - name: Set ENV
        id: env
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
          else
            echo "ENV=dev" >> $GITHUB_OUTPUT
          fi

      - name: Build iOS
        run: |
          flutter build ios --release \
          --no-codesign \
          --dart-define=ENV=${{ steps.env.outputs.ENV }} \
          --dart-define=BASE_URL=${{ secrets.BASE_URL }} \
          --dart-define=API_KEY=${{ secrets.API_KEY }}

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-${{ steps.env.outputs.ENV }}
          path: build/ios/iphoneos/